### ISSUE TITLE
How to lock the screen use af 3  demo at ios

### ISSUE THREAD

**Issue by lankster** [01org/appframework#856]
The af 3 demo run iOS simulator with untouch
--------------------------------------------

![enter image description here](https://dn-fatcoder.qbox.me/iOS%20Simulator%20Screen%20Shot%202015%E5%B9%B44%E6%9C%8822%E6%97%A5%20%E4%B8%8A%E5%8D%8810.27.42.png)

When the content is less than the page' height, pull down the screen,how would I solve this problem？
--------------------------------------------

![enter image description here](https://dn-fatcoder.qbox.me/iOS%20Simulator%20Screen%20Shot%202015%E5%B9%B44%E6%9C%8822%E6%97%A5%20%E4%B8%8A%E5%8D%8810.26.32.png)

**Comment by imaffett** [comment]
Please post demos, device and OS types you are testing on

**Comment by lankster** [comment]
The demo that is clone from AF3.0 project page without change  ( https://github.com/01org/appframework.git ).
put the code in Cordova project.
Cordova version 4.12 & 5.0
OS: iOS 
all of OS's version
device&iOS simulator

**Comment by imaffett** [comment]
Hopefully someone else can look into this later.  It seems to be reporting an incorrect heigh in calculation.   It does not happen in Safari.

And which physical device are you testing against?

**Comment by lankster** [comment]
device:iPhone 5c&5 iOS 8.12
It does not happen in Chrome & Chrome use emulation with any phone model

**Comment by lankster** [comment]
if the content is more than the page' height that no happen (AF3.0 with Cordova)

**Comment by imaffett** [comment]
Ok - I looked into this more.  This is working as intended.  The scroll height is bigger then the viewport so you can scroll down.  If it's smaller, you cannot pull it down.  Keep in mind padding/margins count for it.

This is working as intended.  Since we do not provide a scrolling library anymore, we do not provide fixes like AF 2.2 did.  You are free to bring a JS based scroller if you want.
